import Link from "next/link";
import { notFound } from "next/navigation";
import { getRequest } from "@/server/application/request-service";
import { MockAiProvider } from "@/server/infrastructure/ai-provider";

export default async function RequestDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const request = getRequest(id);
  if (!request) notFound();
  const draft = await new MockAiProvider().generateReplyDraft(request);
  return <main className="min-h-screen p-6 md:p-10"><div className="mx-auto max-w-6xl"><Link href="/requests" className="text-sm font-semibold text-blue-600">← Solicitações</Link><div className="mt-6 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-blue-600">{request.clientName} · {request.department}</p><h1 className="mt-1 text-3xl font-bold">{request.subject}</h1><p className="mt-2 text-slate-500">Prazo: {request.dueAt} · Responsável: {request.assignee ?? "Não atribuído"}</p></div><span className="badge bg-amber-100 text-amber-800">{request.priority}</span></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.4fr_1fr]"><section className="space-y-6"><div className="card p-6"><h2 className="font-bold">Contexto da solicitação</h2><p className="mt-4 leading-7 text-slate-600">{request.description}</p></div><div className="card p-6"><h2 className="font-bold">Tarefas relacionadas</h2>{request.tasks.length ? request.tasks.map((task) => <div className="mt-4 flex items-center justify-between border-b pb-3 text-sm" key={task.id}><span>{task.title}</span><span className="text-slate-500">{task.status}</span></div>) : <p className="mt-4 text-sm text-slate-500">Nenhuma tarefa criada.</p>}<button className="mt-5 rounded-lg border px-4 py-2 text-sm font-bold">+ Criar tarefa</button></div></section><aside className="card h-fit p-6"><div className="flex items-center justify-between"><h2 className="font-bold">Assistência de IA</h2><span className="badge bg-blue-50 text-blue-700">Rascunho</span></div><p className="mt-3 text-xs font-semibold text-amber-700">Sugestão gerada por IA — revise antes de usar.</p><p className="mt-4 rounded-lg bg-slate-50 p-4 text-sm leading-6 text-slate-700">{draft.content}</p><p className="mt-4 text-xs text-slate-500">Confiança: {draft.confidence}. Fontes internas: {draft.sourceIds.length}.</p><div className="mt-5 flex gap-2"><button className="rounded-lg border px-3 py-2 text-sm font-bold">Editar</button><button className="rounded-lg bg-blue-600 px-3 py-2 text-sm font-bold text-white">Aprovar</button></div></aside></div></div></main>;
}
